### ISSUE TITLE
(Bug) Wrong path to favicon.svg when hosted in a subdirectory in simple mode

### ISSUE THREAD

**Issue by Erlotinib** [alam00000/bentopdf#296]
## Type of Issue

Please check one:

- [X] 🐛 Bug Report 
- [ ] 💡 Feature Request 
- [ ] ❓ Question / Help 

---

## Description

Hello, 

I self host bentopdf in simple mode (SIMPLE_MODE=true) in a subdirectory (BASE_URL=/bento/) behind an apache server.

When I open the website, favicon.svg is not displayed (I get a 404).

The issue seems to come from [main.ts](https://github.com/alam00000/bentopdf/blob/370968e19994ced94a7b63e1fe898d1d53d730e7/src/js/main.ts#L31) (lines 31 and 99) and maybe [simple-mode-footer.ts ](https://github.com/alam00000/bentopdf/blob/370968e19994ced94a7b63e1fe898d1d53d730e7/src/js/utils/simple-mode-footer.ts#L18) where the path is inserted without being rewritten.

```
[jules@server dist]$ grep -Ri '="/images/favicon.svg' *
assets/main-BfSqhrSe.js:                <img src="/images/favicon.svg" alt="Bento PDF Logo" class="h-8 w-8">
assets/main-BfSqhrSe.js:                  <img src="/images/favicon.svg" alt="Bento PDF Logo" class="h-8 w-8 mr-2">
assets/simple-mode-footer-CUFbIXN-.js:              <img src="/images/favicon.svg" alt="Bento PDF Logo" class="h-8 w-8 mr-2">
```

If I edit the above paths to /bento/xxx in built files, favicon.svg is correctly displayed on all pages.

thanks
Jules

**Comment by alam00000** [comment]
It's been fixed in latest version

**Comment by Erlotinib** [comment]
Hello, 

the bug is still present with latest git from this evening (659a4b1a327a0e03387ad0a9bdc5dfc61ced5f09)
